<p><a href="https://yoomoney.ru/to/410014804048472">ДЛЯ СПОНОРОВ: 4100 1480 4048 472</a></p>
                    <iframe src="https://yoomoney.ru/quickpay/fundraise/button?billNumber=2uyu4wR96GM.230618&" width="330" height="50" frameborder="0" allowtransparency="true" scrolling="no"></iframe>
